name: Ejecución de Pruebas Python

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout del código
    - name: Checkout código
      uses: actions/checkout@v4

    # 2. Configuración de Python
    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    # 3. Cache de dependencias
    - name: Cache de dependencias
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: ${{ runner.os }}-pip-

    # 4. Instalación de dependencias
    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov
        [ -f requirements.txt ] && pip install -r requirements.txt

    # 5. Ejecución de pruebas con cobertura
    - name: Ejecutar pruebas con cobertura
      run: |
        pytest tests/ \
          --cov=src \
          --cov-report=xml \
          --junitxml=test-results.xml
      env:
        PYTHONPATH: ${{ github.workspace }}

    # 6. Subir reporte de cobertura a Codecov
    - name: Subir reporte de cobertura
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml