name: Ejecuci贸n de Pruebas Python

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout del c贸digo
    - name: Checkout c贸digo
      uses: actions/checkout@v4

    # 2. Configuraci贸n de Python
    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    # 3. Verificar estructura
    - name: Verificar estructura de tests
      run: |
        echo "Contenido de src/backend/app:"
        ls -la src/backend/app/
        echo "Contenido del directorio tests:"
        ls -la src/backend/app/tests/

    # 4. Instalar dependencias
    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov
        [ -f requirements.txt ] && pip install -r requirements.txt

    # 5. Ejecutar pruebas
    - name: Ejecutar pruebas con cobertura
      run: |
        cd src/backend/app
        PYTHONPATH=$PYTHONPATH:$(pwd)/../.. pytest tests/ \
          --cov=. \
          --cov-report=xml:../../../coverage.xml \
          --junitxml=../../../test-results.xml
      env:
        PYTHONPATH: ${{ github.workspace }}

    # 6. Subir reporte de cobertura
    - name: Subir reporte de cobertura
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml