name: SonarCloud Analysis

on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main"]

jobs:
  analyze:
    name: Analyze with SonarCloud
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      checks: write

    steps:
    # 1. Checkout del código
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # 2. Configurar Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    # 3. Verificar estructura del proyecto
    - name: Verificar estructura del proyecto
      run: |
        echo "Estructura del proyecto:"
        ls -R src/backend/app || echo "El directorio src/backend/app no existe"

    # 4. Instalar dependencias
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov
        [ -f requirements.txt ] && pip install -r requirements.txt

    # 6. Ejecutar pruebas
    - name: Run tests
      run: |
        cd src/backend/app
        PYTHONPATH=$PYTHONPATH:$(pwd)/../.. pytest tests/ \
          --cov=. \
          --cov-report=xml:../../../coverage.xml \
          --junitxml=../../../test-results.xml

    # 7. Análisis SonarCloud
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.projectKey=ISCODEVUTB_ConstructionCompany
          -Dsonar.organization=deviscoutb
          -Dsonar.python.version=3.12
          -Dsonar.sources=./src/backend/app
          -Dsonar.tests=./src/backend/app/tests
          -Dsonar.python.coverage.reportPaths=coverage.xml
          -Dsonar.python.xunit.reportPath=test-results.xml
          -Dsonar.exclusions=src/frontend/**,**/__pycache__/**,**/*.md,**/*.json,**/*.dart
          -Dsonar.working.directory=.
          -Dsonar.verbose=true