name: SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and analyze on SonarCloud
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Evita shallow clone para que SonarCloud pueda obtener el historial completo

      # 2. Configurar Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.0'  # Puedes ajustar la versión según lo necesario

      # 3. Instalar dependencias
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-cov

      # 4. Ejecutar pruebas con cobertura
      - name: Run tests with coverage
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          pytest tests --cov=backend --cov-report=xml --junitxml=test-reports.xml

      # 5. Preparar los datos de cobertura de pruebas
      # Si los archivos de cobertura tienen rutas incorrectas, puedes ajustarlas con un script 'sed'
      - name: Fix Coverage File Paths
        run: |
          sed -i 's|/workspaces/ConstructionCompany/|/github/workspace/|g' coverage.xml

      # 6. Ejecutar análisis de SonarCloud
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Necesario para obtener información de PR
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}    # Token generado en SonarCloud
        with:
          args: >
            -Dsonar.projectKey=ISCODEVUTB_ConstructionCompany
            -Dsonar.organization=deviscoutb
            -Dsonar.python.version=3.12
            -Dsonar.coverageReportPaths=coverage.xml
            -Dsonar.junit.reportPaths=test-reports.xml
            -X
