name: SonarCloud Analysis

on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main"]

jobs:
  analyze:
    name: Analyze with SonarCloud
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      checks: write

    steps:
    # 1. Checkout del código
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # 2. Configurar Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    # 3. Verificar estructura del proyecto
    - name: Verificar estructura del proyecto
      run: |
        echo "Estructura del proyecto:"
        ls -R src/backend/app || echo "El directorio src/backend/app no existe"

    # 4. Verificar contexto de ejecución
    - name: Verificar contexto de ejecución
      run: |
        echo "Directorio actual:"
        pwd
        echo "Archivos en el directorio actual:"
        ls -R

    # 5. Verificar permisos de archivos
    - name: Verificar permisos de archivos
      run: |
        echo "Permisos de archivos en src/backend/app:"
        ls -lR src/backend/app

    # 6. Instalar dependencias
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov
        [ -f requirements.txt ] && pip install -r requirements.txt

    # 7. Ejecutar pruebas
    - name: Run tests
      run: |
        cd src/backend/app
        PYTHONPATH=$PYTHONPATH:$(pwd)/../.. pytest tests/ \
          --cov=. \
          --cov-report=xml:../../../coverage.xml \
          --junitxml=../../../test-results.xml

    # 8. Verificar estructura antes del análisis SonarCloud
    - name: Estructura antes del análisis SonarCloud
      run: ls -R

    # 9. Análisis SonarCloud
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.projectKey=ISCODEVUTB_ConstructionCompany
          -Dsonar.organization=deviscoutb
          -Dsonar.sources=src/backend/app
          -Dsonar.tests=src/backend/app/tests
          -Dsonar.python.version=3.12
          -Dsonar.python.coverage.reportPaths=coverage.xml
          -Dsonar.python.xunit.reportPath=test-results.xml
          -Dsonar.verbose=true

